### ISSUE TITLE
Pywit AssertionError

### ISSUE THREAD

**Issue by Xilpex** [wit-ai/pywit#111]
Hello. When I use this code :

`from wit import Wit`
`access_token = "MY ACCESS TOKEN"`
`client = Wit(access_token=access_token)`
 `client.interactive()`

I get this error:
`Traceback (most recent call last):
  File "/Users/arkumar/wit-ai_tests/wit-ai test1.py", line 12, in <module>
    client.interactive()
  File "/Library/Python/2.7/site-packages/wit/wit.py", line 104, in interactive
    message = prompt(INTERACTIVE_PROMPT, history=history, mouse_support=True).rstrip()
  File "/Library/Python/2.7/site-packages/prompt_toolkit/shortcuts.py", line 548, in prompt
    eventloop=eventloop)
  File "/Library/Python/2.7/site-packages/prompt_toolkit/shortcuts.py", line 576, in run_application
    output=create_output(true_color=true_color))
  File "/Library/Python/2.7/site-packages/prompt_toolkit/shortcuts.py", line 126, in create_output
    ansi_colors_only=ansi_colors_only, term=term)
  File "/Library/Python/2.7/site-packages/prompt_toolkit/terminal/vt100_output.py", line 424, in from_pty
    assert stdout.isatty()
AssertionError
`

Can somebody please help!

**Comment by stopachka** [comment]
hey @Xilpex -- we would need to see what exactly the AssertionError is (i.e a larger stackstrace) -- assuming this is stale, but feel free to make a new post if still experiencing issues
