### ISSUE TITLE
Error running examples/quickstart.py

### ISSUE THREAD

**Issue by delip** [wit-ai/pywit#20]
I'm following the [London/Weather quickstart example](https://wit.ai/docs/quickstart). Instead of the Node invocation, I am using pywit. I am getting this error, I don't know how to resolve:

```
Traceback (most recent call last):
  File "quickstart.py", line 44, in <module>
    client.run_actions(session_id, 'weather in London', {})
  File "/Users/delip/miniconda2/envs/ceye/lib/python2.7/site-packages/wit/wit.py", line 63, in run_actions
    rst = self.converse(session_id, message, context)
  File "/Users/delip/miniconda2/envs/ceye/lib/python2.7/site-packages/wit/wit.py", line 53, in converse
    return req(self.access_token, 'POST', '/converse', params, context)
  File "/Users/delip/miniconda2/envs/ceye/lib/python2.7/site-packages/wit/wit.py", line 19, in req
    json=payload,
  File "/Users/delip/miniconda2/envs/ceye/lib/python2.7/site-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
TypeError: request() got an unexpected keyword argument 'json'
```

Python version:
```
$ python --version
Python 2.7.11 :: Anaconda 2.5.0 (x86_64)
```

Env listing:
```
dependencies:
- abstract-rendering=0.5.1=np110py27_0
- alabaster=0.7.7=py27_0
- anaconda=2.5.0=np110py27_0
- anaconda-client=1.2.2=py27_0
- appnope=0.1.0=py27_0
- appscript=1.0.1=py27_0
- argcomplete=1.0.0=py27_1
- astropy=1.1.1=np110py27_0
- babel=2.2.0=py27_0
- backports_abc=0.4=py27_0
- beautifulsoup4=4.4.1=py27_0
- bitarray=0.8.1=py27_0
- blaze-core=0.9.0=py27_0
- bokeh=0.11.0=py27_0
- boto=2.39.0=py27_0
- bottleneck=1.0.0=np110py27_0
- cdecimal=2.3=py27_0
- cffi=1.2.1=py27_0
- click=6.3=py27_0
- cloudpickle=0.1.1=py27_0
- clyent=1.2.0=py27_0
- colorama=0.3.6=py27_0
- configobj=5.0.6=py27_0
- cryptography=1.0.2=py27_0
- curl=7.45.0=0
- cycler=0.9.0=py27_0
- cymem=1.30=py27_0
- cython=0.23.4=py27_1
- cytoolz=0.7.5=py27_0
- datashape=0.5.0=py27_0
- decorator=4.0.6=py27_0
- docutils=0.12=py27_0
- dynd-python=0.7.1=py27_0
- enum34=1.1.2=py27_0
- et_xmlfile=1.0.1=py27_0
- fastcache=1.0.2=py27_0
- flask=0.10.1=py27_1
- freetype=2.5.5=0
- funcsigs=0.4=py27_0
- futures=3.0.3=py27_0
- gevent=1.0.2=py27_0
- gevent-websocket=0.9.5=py27_0
- greenlet=0.4.9=py27_0
- grin=1.2.1=py27_1
- h5py=2.5.0=np110py27_4
- hdf5=1.8.15.1=2
- idna=2.0=py27_0
- ipaddress=1.0.14=py27_0
- ipykernel=4.2.2=py27_0
- ipython=4.1.2=py27_1
- ipython-notebook=4.0.4=py27_0
- ipython-qtconsole=4.0.1=py27_0
- ipython_genutils=0.1.0=py27_0
- ipywidgets=4.1.1=py27_0
- itsdangerous=0.24=py27_0
- jbig=2.1=0
- jdcal=1.2=py27_0
- jedi=0.9.0=py27_0
- jinja2=2.8=py27_0
- joblib=0.9.4=py27_0
- jpeg=8d=1
- jsonschema=2.4.0=py27_0
- jupyter=1.0.0=py27_1
- jupyter_client=4.1.1=py27_0
- jupyter_console=4.1.0=py27_0
- jupyter_core=4.0.6=py27_0
- launcher=1.0.0=3
- libdynd=0.7.1=0
- libpng=1.6.17=0
- libtiff=4.0.6=1
- libxml2=2.9.2=0
- libxslt=1.1.28=2
- llvmlite=0.8.0=py27_0
- lxml=3.5.0=py27_0
- markupsafe=0.23=py27_0
- matplotlib=1.5.1=np110py27_0
- mistune=0.7.1=py27_0
- mkl=11.3.1=0
- mkl-service=1.1.2=py27_0
- multipledispatch=0.4.8=py27_0
- murmurhash=0.26.1=py27_0
- nbconvert=4.1.0=py27_0
- nbformat=4.0.1=py27_0
- networkx=1.11=py27_0
- nltk=3.2=py27_0
- node-webkit=0.10.1=0
- nose=1.3.7=py27_0
- notebook=4.1.0=py27_0
- numba=0.23.1=np110py27_0
- numexpr=2.4.6=np110py27_1
- numpy=1.10.4=py27_0
- odo=0.4.0=py27_0
- openpyxl=2.3.2=py27_0
- openssl=1.0.2g=0
- pandas=0.18.0=np110py27_0
- path.py=8.1.2=py27_1
- patsy=0.4.0=np110py27_0
- pep8=1.7.0=py27_0
- pexpect=3.3=py27_0
- pickleshare=0.5=py27_0
- pillow=3.1.0=py27_0
- pip=8.1.1=py27_1
- plac=0.9.1=py27_0
- ply=3.8=py27_0
- preshed=0.46.2=py27_0
- psutil=3.4.2=py27_0
- ptyprocess=0.5=py27_0
- py=1.4.31=py27_0
- pyasn1=0.1.9=py27_0
- pyaudio=0.2.7=py27_0
- pycosat=0.6.1=py27_0
- pycparser=2.14=py27_0
- pycrypto=2.6.1=py27_0
- pycurl=7.19.5.3=py27_0
- pyflakes=1.0.0=py27_0
- pygments=2.1=py27_0
- pyopenssl=0.15.1=py27_1
- pyparsing=2.0.3=py27_0
- pyqt=4.11.4=py27_1
- pytables=3.2.2=np110py27_0
- pytest=2.8.5=py27_0
- python=2.7.11=0
- python-dateutil=2.4.2=py27_0
- python.app=1.2=py27_4
- pytz=2015.7=py27_0
- pyyaml=3.11=py27_1
- pyzmq=15.2.0=py27_0
- qt=4.8.7=1
- qtconsole=4.1.1=py27_0
- readline=6.2=2
- redis=2.6.9=0
- redis-py=2.10.3=py27_0
- requests=2.9.1=py27_0
- rope=0.9.4=py27_1
- scikit-image=0.11.3=np110py27_0
- scikit-learn=0.17=np110py27_2
- scipy=0.17.0=np110py27_0
- semver=2.4.1=py27_0
- setuptools=20.2.2=py27_0
- simplegeneric=0.8.1=py27_0
- simplejson=3.8.2=py27_0
- singledispatch=3.4.0.3=py27_0
- sip=4.16.9=py27_0
- six=1.10.0=py27_0
- snowballstemmer=1.2.1=py27_0
- sockjs-tornado=1.0.1=py27_0
- spacy=0.100.6=py27_1
- sphinx=1.3.5=py27_0
- sphinx_rtd_theme=0.1.9=py27_0
- sputnik=0.9.3=py27_0
- spyder=2.3.8=py27_0
- spyder-app=2.3.8=py27_0
- sqlalchemy=1.0.11=py27_0
- sqlite=3.9.2=0
- ssl_match_hostname=3.4.0.2=py27_0
- statsmodels=0.6.1=np110py27_0
- sympy=0.7.6.1=py27_0
- terminado=0.5=py27_1
- thinc=5.0.6=py27_1
- tk=8.5.18=0
- toolz=0.7.4=py27_0
- tornado=4.3=py27_0
- traitlets=4.1.0=py27_0
- ujson=1.35=py27_0
- unicodecsv=0.14.1=py27_0
- werkzeug=0.11.3=py27_0
- wheel=0.29.0=py27_0
- xlrd=0.9.4=py27_0
- xlsxwriter=0.8.4=py27_0
- xlwings=0.6.4=py27_0
- xlwt=1.0.0=py27_0
- xz=5.0.5=0
- yaml=0.1.6=0
- zeromq=4.1.3=0
- zlib=1.2.8=0
- pip:
  - arrow==0.7.0
  - awscli==1.6.2
  - backports-abc==0.4
  - backports.ssl-match-hostname==3.5.0.1
  - bcdoc==0.12.2
  - blaze==0.9.0
  - botocore==0.73.0
  - bz2file==0.98
  - cachecontrol==0.11.6
  - certifi==2015.4.28
  - climate==0.4.6
  - contextlib2==0.5.1
  - downhill==0.3.2
  - dynd==f641248
  - elasticsearch==2.3.0
  - et-xmlfile==1.0.1
  - fuel==0.0.1
  - functools32==3.2.3.post2
  - funcy==1.7.1
  - future==0.15.2
  - gensim==0.12.4
  - genson==0.1.0
  - gnureadline==6.3.3
  - graphlab-create==1.8.5
  - graphlab-create-license==1.8.5
  - httpretty==0.8.10
  - intervaltree==2.1.0
  - ipyparallel==5.0.1
  - ipython-genutils==0.1.0
  - jmespath==0.5.0
  - jupyter-client==4.1.1
  - jupyter-console==4.1.0
  - jupyter-core==4.0.6
  - keras==0.3.2
  - lime==0.1.1.3
  - lockfile==0.12.2
  - mixpanel-py==3.1.1
  - mock==1.3.0
  - mpld3==0.2
  - natsort==4.0.4
  - ndg-httpsclient==0.4.0
  - neurolab==0.3.5
  - numpydoc==0.6.0
  - pbr==1.8.1
  - picklable-itertools==0.1.0
  - plotly==1.8.6
  - prettytable==0.7.2
  - progressbar2==2.7.3
  - pybrain==0.3
  - pyldavis==1.5.0
  - pymongo==3.2.2
  - pyreadline==2.1
  - rep==0.6.5
  - rsa==3.1.2
  - scikit-bio==0.4.2
  - slackclient==1.0.0
  - smart-open==1.3.2
  - sortedcontainers==1.4.4
  - sphinx-rtd-theme==0.1.9
  - sseclient==0.0.8
  - tables==3.2.0
  - testpath==0.3
  - theanets==0.6.2
  - theano==0.8.0
  - urllib3==1.14
  - websocket-client==0.35.0
  - wit==3.1
  - xgboost==0.4a30
```

**Comment by patapizza** [comment]
Thanks, it should work now.

**Comment by rithvikvibhu** [comment]
pip not updated with this patch. Had to install from source to get it to work.
