### ISSUE TITLE
Latest change to quickstart.py not working

### ISSUE THREAD

**Issue by ThorodanBrom** [wit-ai/pywit#70]
The latest commit to quickstart.py [https://github.com/wit-ai/pywit/commit/a46417b6a91bcdf947e2cbfcd2af189457ee64f3](url) is simply not working, it gives a KeyError. Another issue, on a sidenote is that the [https://wit.ai/ar7hur/Quickstart](url) link simply does not display any content, besides the page borders.
Below is the console O/P. I made the story that was described in the general Quickstart(the one with node) and displayed the context value in the GetForecast function
`
> we
{}
Where?
> colombo
{'missingLocation': True}
Weather = sunny
> hows the weather in india?
{'forecast': 'sunny'}
Traceback (most recent call last):
  File "quickstart.py", line 45, in <module>
    client.interactive()
  File "build/bdist.linux-x86_64/egg/wit/wit.py", line 210, in interactive
  File "build/bdist.linux-x86_64/egg/wit/wit.py", line 176, in run_actions
  File "build/bdist.linux-x86_64/egg/wit/wit.py", line 150, in __run_actions
  File "quickstart.py", line 31, in get_forecast
    del context['missingLocation']
KeyError: 'missingLocation'`

**Comment by louis9171** [comment]
#71 Hopefully this should solve the problem

**Comment by patapizza** [comment]
Merged, thanks!
