### ISSUE TITLE
Can't convert NoneType to str implicitly

### ISSUE THREAD

**Issue by sils** [wit-ai/pywit#77]
```
127.0.0.1 - - [06/Jan/2017 18:52:33] "POST /webhook HTTP/1.0" 500 2088
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/lib/python3.5/dist-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "./bot.py", line 48, in messenger_post
    client.run_actions(session_id=fb_id, message=text)
  File "/usr/local/lib/python3.5/dist-packages/wit/wit.py", line 176, in run_actions
    context, max_steps, verbose)
  File "/usr/local/lib/python3.5/dist-packages/wit/wit.py", line 159, in __run_actions
    i - 1, verbose)
  File "/usr/local/lib/python3.5/dist-packages/wit/wit.py", line 159, in __run_actions
    i - 1, verbose)
  File "/usr/local/lib/python3.5/dist-packages/wit/wit.py", line 149, in __run_actions
    self.throw_if_action_missing(action)
  File "/usr/local/lib/python3.5/dist-packages/wit/wit.py", line 214, in throw_if_action_missing
    raise WitError('unknown action: ' + action_name)
TypeError: Can't convert 'NoneType' object to str implicitly
```

I wonder why it has `None` as an action? That seems the case at least.

**Comment by sils** [comment]
dupe of https://github.com/wit-ai/pywit/issues/64
