### ISSUE TITLE
Wit Not Predicting Actions, Giving "Unknown Action" Error

### ISSUE THREAD

**Issue by Giada-Z** [wit-ai/pywit#84]
Link to my app: [https://wit.ai/jiajiazhang/Gooroo/stories](url)

Basically if the user selects "Ask questions", the bot is supposed to decide whether it should take the question or not.
<img width="712" alt="screen shot 2017-03-28 at 11 28 02 am" src="https://cloud.githubusercontent.com/assets/16948411/24413532/b22686f0-13a9-11e7-88a6-fbd20aba9586.png">

However, my app does not execute the "receiveAction" action and gives the following error:
_Traceback (most recent call last):
  File "simpletest.py", line 513, in <module>
    client.interactive()
  File "/Users/Jiajia/.virtualenvs/test-bot/lib/python2.7/site-packages/wit/wit.py", line 210, in interactive
    context = self.run_actions(session_id, message, context, max_steps)
  File "/Users/Jiajia/.virtualenvs/test-bot/lib/python2.7/site-packages/wit/wit.py", line 176, in run_actions
    context, max_steps, verbose)
  File "/Users/Jiajia/.virtualenvs/test-bot/lib/python2.7/site-packages/wit/wit.py", line 149, in __run_actions
    self.throw_if_action_missing(action)
  File "/Users/Jiajia/.virtualenvs/test-bot/lib/python2.7/site-packages/wit/wit.py", line 214, in throw_if_action_missing
    raise WitError('unknown action: ' + action_name)
TypeError: cannot concatenate 'str' and 'NoneType' objects_

When I check the logs on Wit, it seems that wit predicts an action named "action", which does not exist in my story.
<img width="545" alt="screen shot 2017-03-28 at 11 23 12 am" src="https://cloud.githubusercontent.com/assets/16948411/24413234/db79d904-13a8-11e7-9a5a-967f122f073f.png">

Does anyone know what is happening? It had worked well for a long time. Just started to experience the issue recently.

Many thanks!!

**Comment by Giada-Z** [comment]
Issue solved. Just retrain the story.

**Comment by elytaphai** [comment]
Wow
